trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'x64'
  buildConfiguration: 'Release'

steps:

- task: UseDotNet@2
  inputs:
    version: '6.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore Solution'
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    arguments: '--no-restore --configuration $(buildConfiguration)'
  displayName: 'dotnet build $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: 'Run Unit Tests $(BuildConfiguration)'
  inputs:
    command: 'test'
    arguments: '--no-build --configuration $(buildConfiguration) --logger trx --collect "Code Coverage"'
    publishTestResults: true
    failIfCoverageEmpty: True
    projects: '**/LocationApiTests/*.csproj'

- task: DotNetCoreCLI@2
  displayName: 'Publish Project $(BuildConfiguration)'
  inputs:
    command: publish
    publishWebProjects: True
    arguments: '--no-build --configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True

- task: PublishPipelineArtifact@1
  displayName: 'Publish LocationsApi Artifact'
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)' 
    artifactName: 'LocationsApi'